### ISSUE TITLE
Do not error when feed action is invoke with namespace `_`

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-package-kafka#100]
Have the feed action go get the value for namespace if the one pass as parameter is `_`

We are instructing users to unset the namespace here:
https://console.ng.bluemix.net/openwhisk/learn/cli
```
wsk property unset --namespace
```

The feed action will need to handle when user uses the new auth key method and no namespace is configured in the CLI.

Options:
1. Have the feed action do a a OW API call to get the namespace for the authkey
2. Have the runtime provide the namespace string associated with the authkey being used to invoke the feedaction. Today there is a namespace environment variable but it doesn't have the value that we need it has the value of the owner of the action not the namespace associated with the authkey.

**Comment by csantanapr** [comment]
cc @rabbah ^^ see options above about environment variables.

**Comment by rabbah** [comment]
radical idea? we stop allowing users to set namespaces in the cli now.

**Comment by rabbah** [comment]
@csantanapr when the feed action runs, __OW_NAMESPACE is available in the environment for the action; is this not sufficient?

Is the ambiguity around the explicit `namespace` provided by the CLI?
If so, how about the CLI stops doing that? (Radically, the CLI should stop allowing namespace to be set now.)

**Comment by csantanapr** [comment]
@dubeejw @bjustin-ibm It looks like there was a bug that is now fixed in PR https://github.com/openwhisk/openwhisk/pull/1665 pending review and merge.
The bug was that `__OW_NAMESPACE` was always returning `whisk.system` instead of the namespace of the user invoking the shared action.

This means we have a single solution regardless if using old key, new key, we can always retrieve the valid namespace from `process.env['__OW_NAMESPACE']`
