### ISSUE TITLE
update Kafka Log file name for monitoring

### ISSUE THREAD

**Issue by johnsolm** [openwhisk/openwhisk-package-kafka#104]
Looks like we need to have the log file in a certain format in order to be picked up by the log forwarder and eventually viewable in Kibana. Here is the format for the Kafka logs:

kafkaTriggers_log.log

here is how I think they are currently being stored as:

kafkatriggers.log

You also need to print the lines in a format that our current logstash with forwarder can parsed them and send them to ELK

**Comment by bjustin-ibm** [comment]
Ok, can someone define the expected format?

**Comment by johnsolm** [comment]
@cbickel is there a good example for how we should be formatting our log output? thx.

**Comment by cbickel** [comment]
I think, the best format would be the same like in the other modules.
The format of all scala log messages is defined in https://github.com/openwhisk/openwhisk/blob/master/common/scala/src/main/scala/whisk/common/Logging.scala#L113

**Comment by johnsolm** [comment]
Thanks @cbickel

**Comment by johnsolm** [comment]
@bjustin-ibm    

 /**
     * Prints a message to the output stream
     *
     * @param loglevel The level to log on
     * @param id <code>TransactionId</code> to include in the log
     * @param from Reference, where the method was called from.
     * @param message Message to write to the log
     * @param marker A LogMarkerToken. They are defined in <code>LoggingMarkers</code>.
     */
    def emit(loglevel: LogLevel, id: TransactionId, from: AnyRef, message: String, marker: Option[LogMarker] = None) = {
        val now = Instant.now(Clock.systemUTC)
        val time = Emitter.timeFormat.format(now)
        val name = if (from.isInstanceOf[String]) from else Logging.getCleanSimpleClassName(from.getClass)

        val level = loglevel match {
            case DebugLevel   => "DEBUG"
            case InfoLevel    => "INFO"
            case WarningLevel => "WARN"
            case ErrorLevel   => "ERROR"
        }

        val logMessage = Seq(message).collect {
            case msg if msg.nonEmpty =>
                msg.split('\n').map(_.trim).mkString(" ")
        }

        val parts = Seq(s"[$time]", s"[$level]", s"[$id]") ++ Seq(s"[$name]") ++ logMessage ++ marker
        outputStream.println(parts.mkString(" "))
    }

**Comment by bjustin-ibm** [comment]
Looks like `time` needs to be of the form `2017-01-03T14:29:49.330Z`
