### ISSUE TITLE
support for binary message payload

### ISSUE THREAD

**Issue by glikson** [openwhisk/openwhisk-package-kafka#125]
Currently, the message value must be a valid utf-8 string (passed in the JSON payload of the trigger). Removing this limitation would enable many important use-cases for the Kafka feed.
For example, isBinaryData flag could be added, in which case the message value could be base64-encoded.

**Comment by dubeejw** [comment]
@glikson, I am able to reproduce your issue by explicitly encoding the message to be sent from the producer as utf-8. If I don't encode the message as utf-8, I do not receive any error. See the example below. 

Can you show us your producer code?

Produces error:
```
message = bytes([0x8b])
producer.send(topic, message.encode('utf-8'))
```

Does not produce error:
```
message = bytes([0x8b])
producer.send(topic, message)
```

**Comment by glikson** [comment]
It is not my producer - it is coming from the bridge from IoT Platform to Message Hub. The messages are just binary, not utf-8 compliant. So, an attempt to parse them as utf-8 (which was the assumption of MH feed code until now, as far as I understand) was very likely to yield an exception.

**Comment by dubeejw** [comment]
@glikson, the exception is actually thrown from `response = requests.post(self.triggerURL, json=payload, timeout=10.0, verify=check_ssl)`. I'll encode the messages in Base64 before reaching this method call.

**Comment by dubeejw** [comment]
@glikson, from the above post, I meant that I can raise an exception in the consumer by encoding the message in utf-8 from the producer.

**Comment by bjustin-ibm** [comment]
Binary data support for the produce actions is handled by #140
