### ISSUE TITLE
authentication when creating consumers

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk-package-kafka#14]
In order to avoid creating consumers for unauthorized trigger URLs, before creating a new consumer we should somehow authenticate with the OpenWhisk system using the credentials given for the trigger.

**Comment by bjustin-ibm** [comment]
Unfortunately, I just realized that this work really belongs in the feed action. This better follows our principle of keeping the service as dumb (and therefore simple) as possible.

Please reverse the changes in #21 and implement this behavior in the feed action instead.

Sorry for overlooking this 🙁

**Comment by dubeejw** [comment]
@bjustin-ibm, the problem with removing the auth check from app.py is that a user could post a trigger with invalid credentials to our service using Postman.

**Comment by dubeejw** [comment]
@bjustin-ibm, when creating a trigger with invalid credentials using an OpenWhisk deployment, the follow error is displayed: ```
"error": {
     "response": "{\n  \"error\": \"not authorized\", \n  \"success\": false\n}\n",
     "statusCode": 401
}
```

**Comment by bjustin-ibm** [comment]
@dubeejw Ah yes. Good catch!
