### ISSUE TITLE
Improve error handling on trigger fire, do not delete trigger mark it paused instead

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-package-kafka#167]
Currently the trigger is being deleted from the DB on certain error scenarios

We need to improve how do we handle each use case, I think there are 3 use cases when firing

1. Trigger has being removed from OpenWhisk, Controller is reachable and returns Not Found (404)
2. Errors that are not recoverable (wrong auth 403, etc..), then delete trigger from db
3. Errors that with a retry can be succesfully fire on a retry, but never delete the trigger from db, and instead mark the trigger doc in db "paused: true"
4. others?

paused state for triggers is something that could be use when redudancy providers is implemented

**Comment by bjustin-ibm** [comment]
The plan is now to _never_ actually delete triggers automatically. Instead, in scenarios where it is clear that the trigger will not work upon retrying, the trigger is made disabled. Information about why the state has become disabled will be recorded to the trigger record in the DB.

Please pardon the pseudo-code:
```
if !error and statusCode matches 4** and statusCode not in [429, 408]
    // all 400 status codes except 429 (throttle) and 408 (timeout) result in disablement
    disableTrigger(statusCode)
else
   // all other cases enter the current retry behavior (10x attempts, then skip event)
    retry()
```

Disabling the trigger will remove the trigger from memory of the provider as well as update the DB record to indicate that it is no longer active, along with some additional metadata:

```json
{
    "id": "/mynamespace/myTrigger",
    ...
    "status": {
        "active": false,
        "dateChanged": "1492787298588",
        "reason": {
            "kind": "AUTO",
            "statusCode": 404,
            "message": "Feed was automatically disabled due to receiving a 404 when firing the trigger."
        }
    }
}
```

New triggers will be written with a similar `status` property:

```json
{
    "id": "/mynamespace/myTrigger",
    ...
    "status": {
        "active": true,
        "dateChanged": "1492787298588"
    }
}
```

Triggers which already exist in the DB without a `status` property will be assumed to be `active: true`.

Upon booting up, the provider will only instantiate triggers that have `status.active == true` (explicitly or by assumption) and will simply ignore all other triggers in the DB.

This approach has a number of advantages, both immediate and in the near future:
- We no longer mysteriously delete triggers 🎉 
- By recording metadata about why a trigger was automatically disabled, we provide the ability to analyze why a trigger has stopped working. At some point in the future, we may chose to expose this information to the trigger owner (perhaps through a "trigger health" action) that would allow the user to finally understand why their trigger isn't doing what they expect.
- This also enables us to write a tool which scans the DB for triggers that have been long disabled (say, for over a year) and to automatically delete them, if we see the need to do so.
- The `kind` property of `reason` will potentially allow other values such as "ADMIN" to indicate that OW system admins manually made the change.
- This opens the door to eventually allowing users to manually pause and unpause their triggers (`kind: USER`).

**Comment by rabbah** [comment]
It would be nice to build this in such a way that it's reusable for other providers.

**Comment by jasonpet** [comment]
nice write up.

**Comment by csantanapr** [comment]
@rabbah 
>It would be nice to build this in such a way that it's reusable for other providers.

That's the plan for all providers to implement same logic.
currently cloudant and alarms are the ones that can share code, today is technical debt that is duplicate code, hope we can get time to implement common nodejs modules to share between them.
