### ISSUE TITLE
action to post a message to Kafka

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk-package-kafka#18]
The Kafka/Message Hub package should include an action that allows the caller to post a message to some topic in some Kafka or Message Hub instance.

**Comment by bjustin-ibm** [comment]
@glikson Had an interesting suggestion to try to reuse an existing/initialized producer if possible. This may be as simple as declaring the producer in the global namespace and then first checking if this producer exists and has the correct options set. In the case that the action is run in a warm container, this could reduce the overhead of creating/initializing a new producer.

**Comment by csantanapr** [comment]
readme update?

**Comment by dubeejw** [comment]
@csantanapr, README update was in the PR.

**Comment by csantanapr** [comment]
I see action documented in the README but I didn't see the file in this PR https://github.com/openwhisk/openwhisk-package-kafka/pull/127/files

maybe it was in different PR

**Comment by dubeejw** [comment]
@csantanapr, https://github.com/openwhisk/openwhisk-package-kafka/pull/131/files
