### ISSUE TITLE
Don't Attempt to create Trigger if it Already Exists

### ISSUE THREAD

**Issue by dubeejw** [openwhisk/openwhisk-package-kafka#24]
Python errors occur when trying to post a trigger that already exists. We should ensure that the trigger does not exist before attempting to post it.

**Comment by bjustin-ibm** [comment]
As long as the app continues to run without issue, I am inclined to not do anything about this.  Here are my reasons:

I'm trying to make the feed service as dumb as possible. The more code we put into it, the more likely it will be that it needs bug fixes. Instead, the "smarts" are put into the feed action. The feed action is much simpler to deploy a fix, and so we should try to put as much load as possible on it. With that in mind, I think it is generally safe to assume that the feed service will be called only by the feed action, and not directly by users.

The exception I would make to this guideline is the scenario when directly invoking one of these endpoints improperly can result in degradation of the feed service. We must guard against DOS and other malicious uses of the feed service. However, in this specific instance of creating duplicate triggers, as long as the app handles this scenario gracefully, I think we can leave it as-is for the sake of keeping it simple and dumb.

Please feel free to disagree and re-open this issue with your thoughts.
