### ISSUE TITLE
handle when MH instance is deleted

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk-package-kafka#48]
When a trigger exists and the corresponding Message Hub instance is deleted, I believe an exception is thrown (likely from `poll()`)and the consumer thread crashes. While the rest of the service continues, this is a pretty clumsy way to handle the situation.

When this happens, the exception should be caught and message logged, and the consumer should be shut down and cleaned up gracefully.

In the future, there may be a way to indicate this back to the OpenWhisk backend, but for now I think this should suffice.

**Comment by dubeejw** [comment]
An error is also produced when the Docker container is started and the Message Hub credentials for an existing consumer are no longer valid.
