### ISSUE TITLE
Do not Assume all Fields are Provided when a Trigger is Posted

### ISSUE THREAD

**Issue by dubeejw** [openwhisk/openwhisk-package-kafka#56]
Exceptions occur if all the required fields needed to post a trigger are not provided by the client. These exception must be caught, and an appropriate error message must be sent back to the client.

**Comment by bjustin-ibm** [comment]
I guess I'm a little wary of this as it starts to tread on the idea that the service should be as dumb/simple as possible. If I understand correctly, posting without all the required fields causes an exception and the client gets a vague 500 error. But... there is no harm to the service right?

**Comment by bjustin-ibm** [comment]
Resolved by #65
