### ISSUE TITLE
/health endpoint

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk-package-kafka#7]
Implement an endpoint that returns data regarding the health of the feed service provider. Information should include things like:
- average CPU load (past hour? array of averages for each of the past 24 hours?)
- memory usage
- number of active consumers

The caller of this endpoint is interested in determining how much work is being done by the feed service, and how much more work can it do before it is overloaded.

**Comment by bjustin-ibm** [comment]
Other statistical information is also valuable (e.g. average time to process incoming messages, size of messages processed, etc.) but these might be better handled by statistical analysis of the log messages, rather than actively computing these inside the feed service provider itself.

**Comment by bjustin-ibm** [comment]
I suspect this will need to be implemented as a separate thread that wakes up every now and then, computes and records the required information.

**Comment by dubeejw** [comment]
@bjustin-ibm, how do you feel about having a separate thread running that periodically outputs the health information to the logs?

**Comment by bjustin-ibm** [comment]
@dubeejw I suspect that will be necessary in order to provide "average" stats. However, it is possible that the `/health` endpoint could simply return the current values, and some other monitoring system will handle computing averages by periodically polling the `/health` endpoint and recording the results.

For now, let's just make it return the instantaneous values.  Later, if we have a need, we can compute/record values using a separate thread.
