### ISSUE TITLE
api_key is a redundant parameter

### ISSUE THREAD

**Issue by bjustin-ibm** [openwhisk/openwhisk-package-kafka#79]
`api_key == username + password` which means that asking for all three as parameters on the Message Hub feed action is just redundant.

**Comment by bjustin-ibm** [comment]
Since the MH feed already requires lots of parameters, my preference is to get rid of `user` and `password` in favor of just `api_key`.

@csantanapr thoughts?

**Comment by bjustin-ibm** [comment]
@jthomas Do you have any preference here?

**Comment by csantanapr** [comment]
Sounds good to me

**Comment by jthomas** [comment]
Just asking for API key makes sense to me.

**Comment by dubeejw** [comment]
@bjustin-ibm, is api_key needed just for Message Hub, or is it needed for Kafka as well?

**Comment by bjustin-ibm** [comment]
So far, `api_key` is only needed for Message Hub.

**Comment by dubeejw** [comment]
@bjustin-ibm, I see a problem with only using the api_key. We need to pass the username and password to the KafkaConsumer constructor. However, the api_key concatenates the username and password with no delimiter, which wouldn't allow us to obtain the username and password to pass.
